FROM golang:1.10.1

RUN apt-get update && apt-get install -y gcc-arm-linux-gnueabihf

ENV DEP_URL https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
ENV DEP_HASH 31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315

RUN curl -sL -o /usr/local/bin/dep $DEP_URL && \
    echo "${DEP_HASH} /usr/local/bin/dep" | sha256sum -c && \
    chmod +x /usr/local/bin/dep

WORKDIR /go/src/github.com/simonswine/rocklet

ADD Gopkg.toml Gopkg.lock ./
RUN dep ensure -vendor-only
