/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	vacuum_v1alpha1 "github.com/simonswine/rocklet/pkg/apis/vacuum/v1alpha1"
	versioned "github.com/simonswine/rocklet/pkg/client/clientset/versioned"
	internalinterfaces "github.com/simonswine/rocklet/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/simonswine/rocklet/pkg/client/listers/vacuum/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VacuumInformer provides access to a shared informer and lister for
// Vacuums.
type VacuumInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VacuumLister
}

type vacuumInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVacuumInformer constructs a new informer for Vacuum type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVacuumInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVacuumInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVacuumInformer constructs a new informer for Vacuum type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVacuumInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VacuumV1alpha1().Vacuums(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VacuumV1alpha1().Vacuums(namespace).Watch(options)
			},
		},
		&vacuum_v1alpha1.Vacuum{},
		resyncPeriod,
		indexers,
	)
}

func (f *vacuumInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVacuumInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vacuumInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vacuum_v1alpha1.Vacuum{}, f.defaultInformer)
}

func (f *vacuumInformer) Lister() v1alpha1.VacuumLister {
	return v1alpha1.NewVacuumLister(f.Informer().GetIndexer())
}
