/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/simonswine/rocklet/pkg/apis/vacuum/v1alpha1"
	scheme "github.com/simonswine/rocklet/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CleaningsGetter has a method to return a CleaningInterface.
// A group's client should implement this interface.
type CleaningsGetter interface {
	Cleanings(namespace string) CleaningInterface
}

// CleaningInterface has methods to work with Cleaning resources.
type CleaningInterface interface {
	Create(*v1alpha1.Cleaning) (*v1alpha1.Cleaning, error)
	Update(*v1alpha1.Cleaning) (*v1alpha1.Cleaning, error)
	UpdateStatus(*v1alpha1.Cleaning) (*v1alpha1.Cleaning, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Cleaning, error)
	List(opts v1.ListOptions) (*v1alpha1.CleaningList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Cleaning, err error)
	CleaningExpansion
}

// cleanings implements CleaningInterface
type cleanings struct {
	client rest.Interface
	ns     string
}

// newCleanings returns a Cleanings
func newCleanings(c *VacuumV1alpha1Client, namespace string) *cleanings {
	return &cleanings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cleaning, and returns the corresponding cleaning object, and an error if there is any.
func (c *cleanings) Get(name string, options v1.GetOptions) (result *v1alpha1.Cleaning, err error) {
	result = &v1alpha1.Cleaning{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cleanings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Cleanings that match those selectors.
func (c *cleanings) List(opts v1.ListOptions) (result *v1alpha1.CleaningList, err error) {
	result = &v1alpha1.CleaningList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cleanings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cleanings.
func (c *cleanings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cleanings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cleaning and creates it.  Returns the server's representation of the cleaning, and an error, if there is any.
func (c *cleanings) Create(cleaning *v1alpha1.Cleaning) (result *v1alpha1.Cleaning, err error) {
	result = &v1alpha1.Cleaning{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cleanings").
		Body(cleaning).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cleaning and updates it. Returns the server's representation of the cleaning, and an error, if there is any.
func (c *cleanings) Update(cleaning *v1alpha1.Cleaning) (result *v1alpha1.Cleaning, err error) {
	result = &v1alpha1.Cleaning{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cleanings").
		Name(cleaning.Name).
		Body(cleaning).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cleanings) UpdateStatus(cleaning *v1alpha1.Cleaning) (result *v1alpha1.Cleaning, err error) {
	result = &v1alpha1.Cleaning{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cleanings").
		Name(cleaning.Name).
		SubResource("status").
		Body(cleaning).
		Do().
		Into(result)
	return
}

// Delete takes name of the cleaning and deletes it. Returns an error if one occurs.
func (c *cleanings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cleanings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cleanings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cleanings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cleaning.
func (c *cleanings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Cleaning, err error) {
	result = &v1alpha1.Cleaning{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cleanings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
