/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/simonswine/rocklet/pkg/apis/vacuum/v1alpha1"
	scheme "github.com/simonswine/rocklet/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VacuumsGetter has a method to return a VacuumInterface.
// A group's client should implement this interface.
type VacuumsGetter interface {
	Vacuums(namespace string) VacuumInterface
}

// VacuumInterface has methods to work with Vacuum resources.
type VacuumInterface interface {
	Create(*v1alpha1.Vacuum) (*v1alpha1.Vacuum, error)
	Update(*v1alpha1.Vacuum) (*v1alpha1.Vacuum, error)
	UpdateStatus(*v1alpha1.Vacuum) (*v1alpha1.Vacuum, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Vacuum, error)
	List(opts v1.ListOptions) (*v1alpha1.VacuumList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Vacuum, err error)
	VacuumExpansion
}

// vacuums implements VacuumInterface
type vacuums struct {
	client rest.Interface
	ns     string
}

// newVacuums returns a Vacuums
func newVacuums(c *VacuumV1alpha1Client, namespace string) *vacuums {
	return &vacuums{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vacuum, and returns the corresponding vacuum object, and an error if there is any.
func (c *vacuums) Get(name string, options v1.GetOptions) (result *v1alpha1.Vacuum, err error) {
	result = &v1alpha1.Vacuum{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vacuums").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Vacuums that match those selectors.
func (c *vacuums) List(opts v1.ListOptions) (result *v1alpha1.VacuumList, err error) {
	result = &v1alpha1.VacuumList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vacuums").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vacuums.
func (c *vacuums) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vacuums").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a vacuum and creates it.  Returns the server's representation of the vacuum, and an error, if there is any.
func (c *vacuums) Create(vacuum *v1alpha1.Vacuum) (result *v1alpha1.Vacuum, err error) {
	result = &v1alpha1.Vacuum{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vacuums").
		Body(vacuum).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vacuum and updates it. Returns the server's representation of the vacuum, and an error, if there is any.
func (c *vacuums) Update(vacuum *v1alpha1.Vacuum) (result *v1alpha1.Vacuum, err error) {
	result = &v1alpha1.Vacuum{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vacuums").
		Name(vacuum.Name).
		Body(vacuum).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *vacuums) UpdateStatus(vacuum *v1alpha1.Vacuum) (result *v1alpha1.Vacuum, err error) {
	result = &v1alpha1.Vacuum{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vacuums").
		Name(vacuum.Name).
		SubResource("status").
		Body(vacuum).
		Do().
		Into(result)
	return
}

// Delete takes name of the vacuum and deletes it. Returns an error if one occurs.
func (c *vacuums) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vacuums").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vacuums) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vacuums").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vacuum.
func (c *vacuums) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Vacuum, err error) {
	result = &v1alpha1.Vacuum{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vacuums").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
