/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/simonswine/rocklet/pkg/apis/vacuum/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCleanings implements CleaningInterface
type FakeCleanings struct {
	Fake *FakeVacuumV1alpha1
	ns   string
}

var cleaningsResource = schema.GroupVersionResource{Group: "vacuum.swine.de", Version: "v1alpha1", Resource: "cleanings"}

var cleaningsKind = schema.GroupVersionKind{Group: "vacuum.swine.de", Version: "v1alpha1", Kind: "Cleaning"}

// Get takes name of the cleaning, and returns the corresponding cleaning object, and an error if there is any.
func (c *FakeCleanings) Get(name string, options v1.GetOptions) (result *v1alpha1.Cleaning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cleaningsResource, c.ns, name), &v1alpha1.Cleaning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cleaning), err
}

// List takes label and field selectors, and returns the list of Cleanings that match those selectors.
func (c *FakeCleanings) List(opts v1.ListOptions) (result *v1alpha1.CleaningList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cleaningsResource, cleaningsKind, c.ns, opts), &v1alpha1.CleaningList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CleaningList{}
	for _, item := range obj.(*v1alpha1.CleaningList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cleanings.
func (c *FakeCleanings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cleaningsResource, c.ns, opts))

}

// Create takes the representation of a cleaning and creates it.  Returns the server's representation of the cleaning, and an error, if there is any.
func (c *FakeCleanings) Create(cleaning *v1alpha1.Cleaning) (result *v1alpha1.Cleaning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cleaningsResource, c.ns, cleaning), &v1alpha1.Cleaning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cleaning), err
}

// Update takes the representation of a cleaning and updates it. Returns the server's representation of the cleaning, and an error, if there is any.
func (c *FakeCleanings) Update(cleaning *v1alpha1.Cleaning) (result *v1alpha1.Cleaning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cleaningsResource, c.ns, cleaning), &v1alpha1.Cleaning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cleaning), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCleanings) UpdateStatus(cleaning *v1alpha1.Cleaning) (*v1alpha1.Cleaning, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cleaningsResource, "status", c.ns, cleaning), &v1alpha1.Cleaning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cleaning), err
}

// Delete takes name of the cleaning and deletes it. Returns an error if one occurs.
func (c *FakeCleanings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cleaningsResource, c.ns, name), &v1alpha1.Cleaning{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCleanings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cleaningsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CleaningList{})
	return err
}

// Patch applies the patch and returns the patched cleaning.
func (c *FakeCleanings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Cleaning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cleaningsResource, c.ns, name, data, subresources...), &v1alpha1.Cleaning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cleaning), err
}
